project:
  type: website

website:
  title: "ISSS626"
  navbar:
    background: secondary
    search: true
    left: 
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on Exercise 1a"
            href: "Hands-on_Exercise/Hands-on_EX01/Hands-on exercise 01.html"
          - text: "Hands-on Exercise 1b"
          - text: "Hands-on Exercise 2"
          - text: "Hands-on Exercise 3"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

