project:
  type: website

website:
  title: "ISSS626"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: 
        text: Hands-on_EX01

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

