project:
  type: website

website:
  title: "ISSS626- GAA"
  navbar:
    background: secondary
    search: true
    left: 
      - text: "In-Class Exercise"
        menu: 
          - text: "In-class Exercise 01"
            href: "In-class Exercise/In-class Exercise 1/In-class_Ex01.html"
          - text: "In-class Exercise 02"
            href: "In-class Exercise/In-class Exercise 2/In-class_Ex02.html"
          - text: "In-class Exercise 03A"
            href: "In-class Exercise/In-class Exercise 3/In-class_Ex03a.html"  
          - text: "In-class Exercise 03B"
            href: "In-class Exercise/In-class Exercise 3/In-class_Ex03b.html"
          - text: "In-class Exercise 04"
            href: "In-class Exercise/In-class Exercise 4/In-class_Ex04.html"
          - text: "In-class Exercise 05"
            href: "In-class Exercise/In-class Exercise 5/In-class_Ex05.html"
      - text: "Take Home Exercise"
        menu: 
          - text: "Take Home Exercise 1"
            href: "Take Home Exercise/Take-Home Exercise 1/Take-Home Exercise 1.html"
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on Exercise 1A"
            href: "Hands-on_Exercise/Hands-on_EX01/Hands-on exercise 01.html"
          - text: "Hands-on Exercise 1B"
            href: "Hands-on_Exercise/Hands-on_EX01/Hands-on exercise 01b.html"
          - text: "Hands-on Exercise 2A"
            href: "Hands-on_Exercise/Hands-on EX02/Chapter 04.html"
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Exercise/Hands-on EX03/Hands-on EX03.html" 
          - text: "Hands-on Exercise 4"
            href: "Hands-on_Exercise/Hands-on EX04/Hands-on EX04.html"
          - text: "Hands-on Exercise 5A"
            href: "Hands-on_Exercise/Hands-on EX05/Hands-on EX05A.html"
          - text: "Hands-on Exercise 5B"
            href: "Hands-on_Exercise/Hands-on EX05/Hands-on EX05B.html"
          - text: "Hands-on Exercise 6"
          - text: "Hands-on Exercise 7"
    right:
      - icon: linkedin
        href: "https://www.linkedin.com/in/kalpit-kulshrestha-a1297b178/"
      - text: "Home"
        href: index.qmd
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

