---
title: "In-class Exercise 6"
author: "Kalpit Kulshrestha"
---

#In-class exercise 6 \## Innstalling the required package

```{r}
pacman::p_load(sf, tidyverse, tmap, sfdep, knitr)
```

```{r}
Busstop = st_read(dsn = "data/LTADataMall/",
                  layer = "BusStop") %>%
  st_transform(crs = 3414)
```

```{r}
mpsz = read_rds("data/rds/mpsz_sf.rds")
glimpse(mpsz)
```

```{r}
odbus <- read_csv("data/LTADataMall/origin_destination_bus_202508.csv")
```

```{r}
tm_shape(mpsz) + 
  tm_polygons() +
tm_shape(Busstop) +
  tm_dots()
```

## joining_left

```{r}
Busstop_in_sg <- st_join(
  Busstop, mpsz,
  join = st_within,
  left = FALSE)
Busstop_in_sg
```

```{r}
tm_shape(mpsz) + 
  tm_polygons() +
tm_shape(Busstop_in_sg) +
  tm_dots()
```

## Deriving Analytical Heaxagon

```{r}
hexagon <- st_make_grid(mpsz,
                        cellsize = 700,
                        what = "polygon",
                        square = FALSE) %>%
  st_sf()     #to convert into simple dataframe
```

## filtering hexagon with bus stops

```{r}
hexagon$n_collisions = 
  lengths(st_intersects(
    hexagon, Busstop_in_sg))

hexagon <- filter(hexagon, n_collisions > 0)
```

## Assigning ids to each hexagon

```{r}
hexagon <- hexagon %>%
  select(, n_collisions)

hexagon$HEX_ID <- sprintf(
  "H%04d", seq_len(nrow(hexagon))) %>%
  as.factor()

kable(head(hexagon))
```

## Preparing Trip Generation Data

### Cleaning the data

```{r}
trips <- odbus %>%
  select(c(ORIGIN_PT_CODE, DAY_TYPE, TIME_PER_HOUR, TOTAL_TRIPS)) %>%
  rename(BUS_STOP_N = ORIGIN_PT_CODE) %>%
  rename(HOUR_OF_DAY = TIME_PER_HOUR) %>%
  rename(TRIPS = TOTAL_TRIPS)
trips$BUS_STOP_N <- as.factor(trips$BUS_STOP_N)
kable(head(trips))
```

```{r}
bs_hex <- st_intersection(
  Busstop, hexagon) %>%
  st_drop_geometry() %>%
  select(c(BUS_STOP_N, HEX_ID))
kable(head(bs_hex))
```

## adding HEX_ID into bus trips data

```{r}
trips <- inner_join(trips, bs_hex)
kable(head(trips))
```
